########################## Adding the three message sections ##################
msg1_sv = StringVar()
msg1_sv.set('Message1')
msg2_sv = StringVar()
msg2_sv.set('Message2')
msg3_sv = StringVar()
msg3_sv.set('Message3')

frame_msg_a = Frame(root, relief = RAISED, borderwidth = 1)
frame_msg_a.pack(fill = X, pady = 1)
msg1_a = Label(frame_msg_a, text = "Message1", bg = "orange")
msg1_a.pack(side = LEFT)
entry_msg1_a = Entry(frame_msg_a, textvariable = msg1_sv)
entry_msg1_a.pack(ipadx= 30, ipady = 10, side=LEFT)
msg2_a = Label(frame_msg_a, text = "Message1", bg = "orange")
msg2_a.pack(side = LEFT, padx = (220, 0))
entry_msg2_a = Entry(frame_msg_a, textvariable = msg1_sv)
entry_msg2_a.pack(ipadx=30, ipady=10, side = LEFT)
msg3_a = Label(frame_msg_a, text = "Message1", bg = "orange")
msg3_a.pack(side = LEFT, padx = (220, 0))
entry_msg3_a = Entry(frame_msg_a, textvariable = msg1_sv)
entry_msg3_a.pack(ipadx=30, ipady=10, side = LEFT)

frame_msg_b = Frame(root, relief = RAISED, borderwidth = 1)
frame_msg_b.pack(fill = X, pady = 1)
msg1_b = Label(frame_msg_b, text = "Message2", bg = "orange")
msg1_b.pack(side = LEFT)
entry_msg1_b = Entry(frame_msg_b, textvariable = msg2_sv)
entry_msg1_b.pack(side = LEFT, ipadx= 30, ipady = 10)
msg2_b = Label(frame_msg_b, text = "Message2", bg = "orange")
msg2_b.pack(side = LEFT, padx = (220, 0))
entry_msg2_b = Entry(frame_msg_b, textvariable = msg2_sv)
entry_msg2_b.pack(side = LEFT, ipadx= 30, ipady = 10)
msg3_b = Label(frame_msg_b, text = "Message2", bg = "orange")
msg3_b.pack(side = LEFT, padx=(220, 0))
entry_msg3_b = Entry(frame_msg_b, textvariable = msg2_sv)
entry_msg3_b.pack(side = LEFT, ipadx= 30, ipady = 10)

frame_msg_c = Frame(root, relief = RAISED, borderwidth = 1)
frame_msg_c.pack(fill = X, pady = 1)
msg1_c = Label(frame_msg_c, text = "Message3", bg = "orange")
msg1_c.pack(side = LEFT)
entry_msg1_c = Entry(frame_msg_c, textvariable = msg3_sv)
entry_msg1_c.pack(side = LEFT, ipadx= 30, ipady = 10)
msg2_c = Label(frame_msg_c, text = "Message3", bg = "orange")
msg2_c.pack(side = LEFT, padx = (220, 0))
entry_msg2_c = Entry(frame_msg_c, textvariable = msg3_sv)
entry_msg2_c.pack(side = LEFT, ipadx= 30, ipady = 10)
msg3_c = Label(frame_msg_c, text = "Message3", bg = "orange")
msg3_c.pack(side = LEFT, padx = (220, 0))
entry_msg3_c = Entry(frame_msg_c, textvariable = msg3_sv)
entry_msg3_c.pack(side = LEFT, ipadx= 30, ipady = 10)
